apiVersion: batch/v1
kind: Job
metadata:
  name: cinegest-back-migrate
  namespace: cinegest
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        fsGroup: 33
      containers:
        - name: migrate
          image: ghcr.io/etho01/cinegest-back:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 33
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: cinegest-back-secret
          command: ["php", "artisan", "migrate", "--force"]