apiVersion: batch/v1
kind: Job
metadata:
  name: cinegest-back-migrate
  namespace: cinegest
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/etho01/cinegest-back:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: cinegest-back-secret
          command: ["php", "artisan", "migrate", "--force"]