apiVersion: v1
kind: Secret
metadata:
  name: cinegest-back-secret
  namespace: cinegest
type: Opaque
stringData:
  APP_NAME: "CineGest"
  APP_ENV: "production"
  APP_KEY: "base64:CHANGE_ME"
  APP_DEBUG: "false"
  APP_URL: "https://api.cinegest.nicolasbarbey.fr"
  APP_FRONTEND_URL: "https://cinegest.nicolasbarbey.fr"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "cinegest"
  DB_USERNAME: "cinegest"
  DB_PASSWORD: "CHANGE_ME"

  SESSION_DRIVER: "database"
  CACHE_STORE: "database"
  QUEUE_CONNECTION: "database"

  SANCTUM_STATEFUL_DOMAINS: "cinegest.nicolasbarbey.fr"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "in-v3.mailjet.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "CHANGE_ME"
  MAIL_PASSWORD: "CHANGE_ME"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "no-reply@cinegest.nicolasbarbey.fr"
  MAIL_FROM_NAME: "CineGest"

  MAILJET_APIKEY: "CHANGE_ME"
  MAILJET_APISECRET: "CHANGE_ME"

  STRIPE_KEY: "CHANGE_ME"
  STRIPE_SECRET: "CHANGE_ME"
  STRIPE_WEBHOOK_SECRET: "CHANGE_ME"