apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: cinegest
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-token
  namespace: cinegest
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
